package com.web.soulyogaadmin.entity;
// Generated Oct 21, 2016 3:11:59 PM by Hibernate Tools 3.2.2.GA

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

	private int adminId;
	private String adminName;
	private String password;
	private Integer adminStatus;

	public Administrator() {
	}

	public Administrator(int adminId) {
		this.adminId = adminId;
	}

	public Administrator(int adminId, String adminName, String password,
			Integer adminStatus) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.password = password;
		this.adminStatus = adminStatus;
	}

	public int getAdminId() {
		return this.adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getAdminStatus() {
		return this.adminStatus;
	}

	public void setAdminStatus(Integer adminStatus) {
		this.adminStatus = adminStatus;
	}

}
