package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private int positionId;
	private String surname;
	private String name;
	private String fristName;
	private String lastName;
	private String mail;
	private String identityId;
	private Integer gender;
	private String avatarUrl;
	private int yogaClubId;
	private int isTeacher;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Employee() {
	}

	public Employee(int positionId, String surname, String name, String fristName, String lastName, int yogaClubId,
			int isTeacher, Date createdTime, int state) {
		this.positionId = positionId;
		this.surname = surname;
		this.name = name;
		this.fristName = fristName;
		this.lastName = lastName;
		this.yogaClubId = yogaClubId;
		this.isTeacher = isTeacher;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Employee(int positionId, String surname, String name, String fristName, String lastName, String mail,
			String identityId, Integer gender, String avatarUrl, int yogaClubId, int isTeacher, Date createdTime,
			Date modifiedTime, int state) {
		this.positionId = positionId;
		this.surname = surname;
		this.name = name;
		this.fristName = fristName;
		this.lastName = lastName;
		this.mail = mail;
		this.identityId = identityId;
		this.gender = gender;
		this.avatarUrl = avatarUrl;
		this.yogaClubId = yogaClubId;
		this.isTeacher = isTeacher;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFristName() {
		return this.fristName;
	}

	public void setFristName(String fristName) {
		this.fristName = fristName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getIdentityId() {
		return this.identityId;
	}

	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public String getAvatarUrl() {
		return this.avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public int getYogaClubId() {
		return this.yogaClubId;
	}

	public void setYogaClubId(int yogaClubId) {
		this.yogaClubId = yogaClubId;
	}

	public int getIsTeacher() {
		return this.isTeacher;
	}

	public void setIsTeacher(int isTeacher) {
		this.isTeacher = isTeacher;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
