package com.web.soulyogaadmin.entity;

import java.util.Date;

/**
 * EmployeeAccount generated by hbm2java
 */
public class EmployeeAccountEntry implements java.io.Serializable {

	private int id;
	private int employeeID;
	private String userName;
	private String password;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public EmployeeAccountEntry() {
	}

	public EmployeeAccountEntry(int id) {
		this.id = id;
	}

	public EmployeeAccountEntry(int id, int employeeID, String userName, String password,
			Date createdTime, Date modifiedTime, int state) {
		this.id = id;
		this.employeeID = employeeID;
		this.userName = userName;
		this.password = password;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEmployeeID() {
		return employeeID;
	}

	public void setEmployeeID(int employeeID) {
		this.employeeID = employeeID;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}


	
}
