package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * EmployeeAccount generated by hbm2java
 */
public class EmployeeAccount implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private int employeeId;
	private String userName;
	private String password;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public EmployeeAccount() {
	}

	public EmployeeAccount(int employeeId, String userName, String password, Date createdTime, int state) {
		this.employeeId = employeeId;
		this.userName = userName;
		this.password = password;
		this.createdTime = createdTime;
		this.state = state;
	}

	public EmployeeAccount(int employeeId, String userName, String password, Date createdTime, Date modifiedTime,
			int state) {
		this.employeeId = employeeId;
		this.userName = userName;
		this.password = password;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
