package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Employeeresetpassword generated by hbm2java
 */
public class Employeeresetpassword implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private String token;
	private Date expiredTime;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Employeeresetpassword() {
	}

	public Employeeresetpassword(int employeeId, String token, Date expiredTime, Date createdTime, int state) {
		this.employeeId = employeeId;
		this.token = token;
		this.expiredTime = expiredTime;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Employeeresetpassword(int employeeId, String token, Date expiredTime, Date createdTime, Date modifiedTime,
			int state) {
		this.employeeId = employeeId;
		this.token = token;
		this.expiredTime = expiredTime;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getExpiredTime() {
		return this.expiredTime;
	}

	public void setExpiredTime(Date expiredTime) {
		this.expiredTime = expiredTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
