package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Employeeaccessresource generated by hbm2java
 */
public class Employeeaccessresource implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private int accessResourceId;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Employeeaccessresource() {
	}

	public Employeeaccessresource(int employeeId, int accessResourceId, Date createdTime, int state) {
		this.employeeId = employeeId;
		this.accessResourceId = accessResourceId;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Employeeaccessresource(int employeeId, int accessResourceId, Date createdTime, Date modifiedTime,
			int state) {
		this.employeeId = employeeId;
		this.accessResourceId = accessResourceId;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public int getAccessResourceId() {
		return this.accessResourceId;
	}

	public void setAccessResourceId(int accessResourceId) {
		this.accessResourceId = accessResourceId;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
