package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Memberloginlog generated by hbm2java
 */
public class Memberloginlog implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private String logInfo;
	private int status;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Memberloginlog() {
	}

	public Memberloginlog(int memberId, String logInfo, int status, Date createdTime, int state) {
		this.memberId = memberId;
		this.logInfo = logInfo;
		this.status = status;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Memberloginlog(int memberId, String logInfo, int status, Date createdTime, Date modifiedTime, int state) {
		this.memberId = memberId;
		this.logInfo = logInfo;
		this.status = status;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public String getLogInfo() {
		return this.logInfo;
	}

	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
