package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer id;
	private String name;
	private String identityId;
	private String mobileNo;
	private int salesConsultantId;
	private String address;
	private Integer gender;
	private Date birthday;
	private String avatarUrl;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Member() {
	}

	public Member(String mobileNo, int salesConsultantId, String address, Date createdTime, int state) {
		this.mobileNo = mobileNo;
		this.salesConsultantId = salesConsultantId;
		this.address = address;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Member(String name, String identityId, String mobileNo, int salesConsultantId, String address,
			Integer gender, Date birthday, String avatarUrl, Date createdTime, Date modifiedTime, int state) {
		this.name = name;
		this.identityId = identityId;
		this.mobileNo = mobileNo;
		this.salesConsultantId = salesConsultantId;
		this.address = address;
		this.gender = gender;
		this.birthday = birthday;
		this.avatarUrl = avatarUrl;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	

	@Override
	public String toString() {
		return "Member [id=" + id + ", name=" + name + ", identityId=" + identityId + ", mobileNo=" + mobileNo
				+ ", salesConsultantId=" + salesConsultantId + ", address=" + address + ", gender=" + gender
				+ ", birthday=" + birthday + ", avatarUrl=" + avatarUrl + ", createdTime=" + createdTime
				+ ", modifiedTime=" + modifiedTime + ", state=" + state + "]";
	}

	public Member(String name, String identityId, String mobileNo, int salesConsultantId, String address,
			Integer gender, Date birthday) {
		super();
		this.name = name;
		this.identityId = identityId;
		this.mobileNo = mobileNo;
		this.salesConsultantId = salesConsultantId;
		this.address = address;
		this.gender = gender;
		this.birthday = birthday;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdentityId() {
		return identityId;
	}

	public void setIdentityId(String identityId) {
		this.identityId = identityId;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public int getSalesConsultantId() {
		return salesConsultantId;
	}

	public void setSalesConsultantId(int salesConsultantId) {
		this.salesConsultantId = salesConsultantId;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getGender() {
		return gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAvatarUrl() {
		return avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	
}
