package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private int departmentId;
	private String positionName;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Position() {
	}

	public Position(int departmentId, Date createdTime, int state) {
		this.departmentId = departmentId;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Position(int departmentId, String positionName, Date createdTime, Date modifiedTime, int state) {
		this.departmentId = departmentId;
		this.positionName = positionName;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
