package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private int employeeId;
	private String introduction;
	private String courseCategoryIds;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Teacher() {
	}

	public Teacher(int employeeId, String courseCategoryIds, Date createdTime, int state) {
		this.employeeId = employeeId;
		this.courseCategoryIds = courseCategoryIds;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Teacher(int employeeId, String introduction, String courseCategoryIds, Date createdTime, Date modifiedTime,
			int state) {
		this.employeeId = employeeId;
		this.introduction = introduction;
		this.courseCategoryIds = courseCategoryIds;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getCourseCategoryIds() {
		return this.courseCategoryIds;
	}

	public void setCourseCategoryIds(String courseCategoryIds) {
		this.courseCategoryIds = courseCategoryIds;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
