package com.web.soulyogaadmin.entity;
// Generated 2017-6-22 13:56:57 by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;

/**
 * Yogaclub generated by hbm2java
 */
public class Yogaclub implements java.io.Serializable {

	private Integer id;
	private String address;
	private String name;
	private String linkman;
	private String phone;
	private String city;
	private Date createdTime;
	private Date modifiedTime;
	private int state;

	public Yogaclub() {
	}

	public Yogaclub(String name, Date createdTime, int state) {
		this.name = name;
		this.createdTime = createdTime;
		this.state = state;
	}

	public Yogaclub(String address, String name, String linkman, String phone, String city, Date createdTime,
			Date modifiedTime, int state) {
		this.address = address;
		this.name = name;
		this.linkman = linkman;
		this.phone = phone;
		this.city = city;
		this.createdTime = createdTime;
		this.modifiedTime = modifiedTime;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(updatable=false)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
